### ISSUE TITLE
Potential scheme_eval issue

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#1179]
There is a potential issue related to calling scheme_eval to get Fluent version info that was resolved by using string_eval. This was in the context of adapting launch_fluent to support launch Fluent docker on the desktop. It will be useful to understand what the issue was.

Original investigation was by @iboyd-ansys.

See also #1178

**Comment by mkundu1** [comment]
As we have different server-side implementation of scheme_eval for 22.2 and 23.1, scheme_eval itself needs to know the Fluent version to correctly parse the return message. string_eval doesn't have any such requirement.

**Comment by mkundu1** [comment]
In PR #1182, I've moved the details within SchemeEval service's constructor, now both scheme_eval and string_eval will work after the service is intialized.

**Comment by iboyd-ansys** [comment]
I hope I didn't cause any confusion but I have realised that I had mixed up the information about what version of Fluent was running when I saw the issue. I thought I was running 23.2 but in fact it was the 23.1 container. I had not set the `FLUENT_IMAGE_TAG` environment variable.

So, to be clear, the `scheme_eval` issue was with 23.1. I have just tried 23.2 and this issue is not present in that case.
