### ISSUE TITLE
Add conda integration

### ISSUE THREAD

**Issue by NSchmidtRose** [pyansys/pyfluent#1276]
### 📝 Description of the feature

Maybe my problem could be solved otherwise, but I am at a loss here. I would also be happy to help test if it works.

I use anaconda to manage my python, so I tried installing ansys-fluent-core using conda. 
To bridge the gap from pip to conda, I used [this](https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fa%2F29304731&data=05%7C01%7Chotline%40cadfem.de%7C15a4c8965333495f713f08daf7d94bb9%7Ca59a38c138844b3dbdf909d16c9da5de%7C0%7C0%7C638094809897294444%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wArSXqmjHVI5%2FCkz02h8YahvDvOPfHGc4Bpp0XW3gO0%3D&reserved=0) guide, replacing skeleton with greyskull (because [this](https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fconda%2Fconda-build%2Fissues%2F4354%23issuecomment-1122948277&data=05%7C01%7Chotline%40cadfem.de%7C15a4c8965333495f713f08daf7d94bb9%7Ca59a38c138844b3dbdf909d16c9da5de%7C0%7C0%7C638094809897294444%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1PqBVflGx4uIKPe9wD%2BylhlmMP5O5mQfk8rwINFij%2FM%3D&reserved=0) says so). I got this error:

conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"ansys-platform-instancemanagement[version='>=1.0,<2.dev0']", 'ansys-api-fluent==0.3.5'}

Does this mean some part of my Fluent installation is too old? If so, which one and why? I am currently using 22R2, but will probably be updating to 23R1 soon.

**Comment by mkundu1** [comment]
We need to build ansys-platform-instancemanagement and ansys-api-fluent within the conda environment before building ansys-fluent-core, because they too aren't available as conda packages. However, their build was failing because conda is expecting setuptools based packaging which they don't have. 

I can directly install pyfluent using pip within conda environment and that seems to be working.
```
conda install pip
pip install ansys-fluent-core
```
More details about using pip in conda environment [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#pip-in-env). Let me know if you're facing any issue with this approach.
