### ISSUE TITLE
Create a new pyansys repository for AFT examples

### ISSUE THREAD

**Issue by mkundu1** [pyansys/pyfluent#608]
As the AFT examples will use pyfluent core and addon (visualization, parametric) packages, a separate github repo is a best place for them. We'll link AFT examples documentation from pyfluent documentation.

**Comment by seanpearsonuk** [comment]
Regarding real world (AFT) examples repo, not sure where we left the idea.



Let's think broadly about this. What might be crucial here is that we don't fragment the whole thing, and we don't create arbitrary separations that are going to be difficult to manage, and more importantly make the documentation harder to appreciate and use.



Apart from the AFT examples, we also have the testing team examples, based on Fluent tutorials. So,

is there any reason to delineate between: 1. AFT examples, 2. tutorial examples, 3. any examples that might come from external contributions in future?

is there really a strong need to differentiate between examples that use 1. visualization, 2. parametric or 3. neither (=core)? Note that 4. both is missing from that list: at the moment such examples would wait to appear in the new repo.

So, I feel that we want to provide a single, comprehensive site to show off all the examples together. What do you think? Then there is a separate, technical question about what goes where in GitHub. We could actually put all examples into a new repo and link to it from each doc site. Or, all the examples could be managed in core repo, which seems less correct. Do we care about using examples for CI, or should we start to rely solely on tests for that? That way we can put all examples into the new repo, make them as realistic as we like, and only run them overnight. Tests, rather than representative examples, should be written to cover everything that could otherwise break examples.


New repo is at https://github.com/pyansys/pyfluent-examples. AFT examples are in .ipynb file, so we need to convert them in the appropriate format for sphinx (there is a way to convert .ipynb -> .py but that still doesn't conform with sphinx - so there is a manual step to fix the docstrings).

Maybe we can document the process and upload couple of examples and AFT team can fill up the rest?

**Comment by seanpearsonuk** [comment]
@dnwillia-work just to update you on this topic, we plan to put all examples together in the new repo at  https://github.com/pyansys/pyfluent-examples. Please ping me if you'd like to discuss further.

**Comment by mkundu1** [comment]
Development is tracked within the new repo.
