### ISSUE TITLE
parallel pytests global fixture data race

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#729]
causing random local test failures at least

**Comment by prmukherj** [comment]
Observation:
1. test_boundaries_elbow(load_mixing_elbow_mesh) in test_boundaries.py
2. test_solver_material(load_mixing_elbow_mesh) in test_materials.py

The above 2 tests are failing while running the entire test script together in local system. However, while re-running the failed tests separately, they are passing. Probable cause might be because they are running parallelly with other tests dependent on the same fixture - load_mixing_elbow_mesh.

A probable fix could be to just use a separate fixture.

**Comment by prmukherj** [comment]
This particular issue is mostly system specific and not reproducible in other systems as of now.

**Comment by seanpearsonuk** [comment]
No longer can we reproduce this
